# File: 'docker-compose.yml'
#
# Folder Structure:
# project-root/
# │
# ├── docker-compose.yml
# ├── Api/
# │   ├── src/
# │         ├── Flickr.Api/
# │              ├── .env
# │   ├── Dockerfile
# │   ├── Flickr.Api.sln
# │
# ├── Web/
# │   ├── src/
# │       ├── [Other HTML project files]
# │   ├── Dockerfile
# │   ├── package.json
#
# Usage:
# 1. Navigate to the project-root directory.
# 2. Run the following command to build and start the containers
#       docker-compose up --build
#
# 3. Access the services
# API: http://localhost:8080
# Web: http://localhost:8001

services:
  flickr-api:
    build:
      context: ./Api  # Point to the folder containing the Dockerfile
      dockerfile: Dockerfile  # The Dockerfile is located directly in the Api folder
    ports:
      - "8080:8080"
    env_file:
      - ./Api/src/Flickr.Api/.env  # Explicitly load the .env file from the Api folder
    networks:
      - flickr-network

  flickr-web:
    build:
      context: ./Web  # Point to the Web folder
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - flickr-api
    networks:
      - flickr-network

networks:
  flickr-network:
    driver: bridge
