# File: 'docker-compose.yml'
#
# Folder Structure:
# project-root/
# │
# ├── docker-compose.yml
# ├── Api/
# │   ├── src/
# │         ├── Flickr.Api/
# │   ├── Dockerfile
# │   ├── Flickr.Api.sln
# │
# ├── Web/
# │   ├── src/
# │   		├── [Other HTML project files]
# │   ├── Dockerfile
# │   ├── package.json
#
# Usage:
# 1. Navigate to the project-root directory.
# 2. Run the following command to build and start the containers
#       docker-compose up --build
#
# 3. Access the services
# API: http://localhost:5000
# Web: http://localhost:3000

version: "0.1"
services:
  flickr-api:
    build:
      context: ./Api/src
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  flickr-web:
    build:
      context: ./Web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - flickr-api
